version = 1.0

[default.deploy.parameters]
stack_name = "soundcloud-proxy"
resolve_s3 = true
s3_prefix = "soundcloud-proxy"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"